name: "Continuous Deployment to main"
on:
  push:
    branches:
      - main

jobs:
  update_infra:
    name: Update Infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Stop running containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_URL }}
          username: "snippet-searcher-admin"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd snippet-infra
            docker compose stop

      - name: Pull latest code
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_URL }}
          username: "snippet-searcher-admin"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd snippet-infra
            git pull

      - name: Start containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_URL }}
          username: "snippet-searcher-admin"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd snippet-infra
            docker compose up -d --build
